### ISSUE TITLE
mobile not working

### ISSUE THREAD

**Issue by inspgadgetNL** [annaghi/mobile-contact-bar#1]
Hello,
I like the plugin alot on a desktop computer, but on a mobile device the plugin only shows crosses as a pictogram, and not the normal images. What can i do to solve this?
Thanks.
Best regards

**Comment by annaghi** [comment]
Hi, try clearing the caches (CSS) and checking if your site has different major versions of Font Awesome. FA 5 and FA 6 might not work together.

**Comment by annaghi** [comment]
Closing this because of silence.
